// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDVA-Ll7RA2oTAu5VLTWydbq-WA3guWYQ',
    appId: '1:845116967360:web:de4ce9e75afb5b1f352025',
    messagingSenderId: '845116967360',
    projectId: 'softecsmeapp',
    authDomain: 'softecsmeapp.firebaseapp.com',
    storageBucket: 'softecsmeapp.firebasestorage.app',
    measurementId: 'G-ZCLJPHB38W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRPAhK3lUO7MKfgM9LGC6v8G69Rk_J4M',
    appId: '1:845116967360:android:fe3c3475a57138b5352025',
    messagingSenderId: '845116967360',
    projectId: 'softecsmeapp',
    storageBucket: 'softecsmeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3JnR88P6nsmBqLEicPyIR8-edmoUTFg8',
    appId: '1:845116967360:ios:1e340a8d4a248c96352025',
    messagingSenderId: '845116967360',
    projectId: 'softecsmeapp',
    storageBucket: 'softecsmeapp.firebasestorage.app',
    iosBundleId: 'com.example.softecSmeApp',
  );

}